Applying intervention: goal
Traceback (most recent call last):
  File "autocalc_curriculum.py", line 681, in <module>
    main()
  File "autocalc_curriculum.py", line 677, in main
    wandb_config=wandb_config
  File "autocalc_curriculum.py", line 499, in train_autocalc_curriculum
    tb_log_name="autocalc_curriculum"
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 243, in learn
    total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 429, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/common/vec_env/vec_monitor.py", line 70, in reset
    obs = self.venv.reset()
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 133, in reset
    obs = [remote.recv() for remote in self.remotes]
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 133, in <listcomp>
    obs = [remote.recv() for remote in self.remotes]
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/kpatherya3/anaconda3/envs/causal_env/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
