Using cuda device
/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/vec_env/patch_gym.py:50: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  "You provided an OpenAI Gym environment. "
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "mfrl_scratch.py", line 151, in <module>
    wandb_config=wandb_config
  File "mfrl_scratch.py", line 89, in train_policy
    seed=seed_num
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/sac/sac.py", line 157, in __init__
    self._setup_model()
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/sac/sac.py", line 160, in _setup_model
    super()._setup_model()
  File "/home/kpatherya3/anaconda3/envs/causal_copy/lib/python3.7/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 196, in _setup_model
    **replay_buffer_kwargs,  # pytype:disable=wrong-keyword-args
TypeError: __init__() got an unexpected keyword argument 'max_episode_length'
